name: Process Bot-Generated Content

on:
  repository_dispatch:
    types: [ add_press, add_thought ]

jobs:
  validate-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Process Content
      id: process-content
      run: |
        # Get date components from payload
        YEAR_MONTH="${{ github.event.client_payload.datetime }}Z"
        YEAR_MONTH=${YEAR_MONTH:0:7}  # Extract YYYY-MM
        TIMESTAMP="${{ github.event.client_payload.datetime }}"

        if [[ "${{ github.event.event_type }}" == "add_press" ]]; then          
          # Create press entry
          CONTENT_DIR="src/bot_gen/selected_press/$YEAR_MONTH"
          mkdir -p "$CONTENT_DIR"
          echo '{
            "url": "${{ github.event.client_payload.url }}",
            "datetime": "'$TIMESTAMP'Z",
            "title": "${{ github.event.client_payload.title }}"
        }' > "$CONTENT_DIR/$TIMESTAMP.json"

        elif [[ "${{ github.event.event_type }}" == "add_thought" ]]; then
          # Create thought entry
          CONTENT_DIR="src/bot_gen/thoughts/$YEAR_MONTH"
          mkdir -p "$CONTENT_DIR"
          echo '{
            "author": "${{ github.event.client_payload.author }}",
            "label": "${{ github.event.client_payload.label }}",
            "css_class": "${{ github.event.client_payload.css_class }}",
            "datetime": "'$TIMESTAMP'Z",
            "content": "${{ github.event.client_payload.content }}"
        }' > "$CONTENT_DIR/$TIMESTAMP.json"
        fi
        echo "::set-output name=timestamp::$TIMESTAMP"

    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@users.noreply.github.com"
        git add src/bot_gen
        git commit -m "Bot: Add new ${{ github.event.type == 'add_press' && 'selected_press' || 'thought' }} entry at ${{ steps.process-content.timestamp }}"
        git push
