name: Create content from telegram bot

on:
  repository_dispatch:
    types: [ add_press, add_thought ]

jobs:
  validate-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      commit_sha: ${{ steps.commit-info.outputs.commit_sha }}
      commit_message: ${{ steps.commit-info.outputs.commit_message }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Process Content
      id: process-content
      run: |
        # Get date components from payload
        YEAR_MONTH="${{ github.event.client_payload.datetime }}Z"
        YEAR_MONTH=${YEAR_MONTH:0:7}  # Extract YYYY-MM
        TIMESTAMP="${{ github.event.client_payload.datetime }}"

        if [[ "${{ github.event.action }}" == "add_press" ]]; then          
          # Create press entry
          CONTENT_DIR="src/bot_gen/selected_press/$YEAR_MONTH"
          mkdir -p "$CONTENT_DIR"
          echo "{
            \"url\": \"${{ github.event.client_payload.url }}\",
            \"datetime\": \"$TIMESTAMP\",
            \"title\": \"${{ github.event.client_payload.title }}\"
        }" > "$CONTENT_DIR/$TIMESTAMP.json"

        elif [[ "${{ github.event.action }}" == "add_thought" ]]; then
          # Create thought entry
          CONTENT_DIR="src/bot_gen/thoughts/$YEAR_MONTH"
          mkdir -p "$CONTENT_DIR"
          echo "{
            \"author\": \"${{ github.event.client_payload.author }}\",
            \"label\": \"${{ github.event.client_payload.label }}\",
            \"css_class\": \"${{ github.event.client_payload.css_class }}\",
            \"datetime\": \"$TIMESTAMP\",
            \"content\": \"${{ github.event.client_payload.content }}\"
        }" > "$CONTENT_DIR/$TIMESTAMP.json"
        fi
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@users.noreply.github.com"
        git add src/bot_gen
        COMMIT_MSG="Bot: Add new ${{ github.event.action == 'add_press' && 'selected_press' || 'thought' }} entry at ${{ steps.process-content.outputs.timestamp}}"
        git commit -m "$COMMIT_MSG"
        git push

    - name: Get commit info
      id: commit-info
      run: |
        echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

  notify:
    needs: validate-and-commit
    runs-on: ubuntu-latest

    steps:
    - name: confirm commit created
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_BOT_CHANNEL }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ needs.validate-and-commit.outputs.commit_message }}

          Repository: ${{ github.repository }}

          See changes: https://github.com/${{ github.repository }}/commit/${{ needs.validate-and-commit.outputs.commit_sha }}
